apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1 # db scaled with stateful-set, not deployment
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp # pod label
    spec:
      containers:
        - name: webapp
          image: nanajanashia/k8s-demo-app:v1.0
          ports:
            - containerPort: 3000
          env:
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: USER_PWD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-url

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort # make service externallly accessible. By default services are internal
  selector:
    app: webapp # should match pod label
  ports:
    - protocol: TCP
      port: 3000 # any port
      targetPort: 3000 # container port
      nodePort: 30100 # node to be exposed externally
